### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by saisaitian** [tomsing1/gCMAP#1]
In fact, when I update my R to 4.03, however, I can not install it in my computer!
![image](https://user-images.githubusercontent.com/26356557/103252784-37455480-49b9-11eb-8b5a-864b20fc1c63.png)

**Comment by tomsing1** [comment]
Hi @saisaitian ,

the `bigmemoryExtras` package is available from [Bioconductor](https://www.bioconductor.org/packages/release/bioc/html/bigmemoryExtras.html). I don't think the `install_github` function searches Bioconductor by default. Please try to install it beforehand:

```r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("bigmemoryExtras")
```

Please note that the `gCMAP` package has been deprecated from Bioconductor and is no longer actively supported.

**Comment by tomsing1** [comment]
I will archive this repository, because I won't be able to provide any support. Feel free to fork it if the code is useful to you!
